### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'function'

### ISSUE THREAD

**Issue by andy121090** [notadamking/tensortrade#10]
**System information**

- OS Platform and Distribution: Ubuntu 18.04.2 LTS
- TensorTrade version: 0.0.1
- TensorFlow version: 1.13.1
- Python version: 3.6.7

**Describe the current behavior**
I try to execute the code of the example _TensorTrade_Tutorial.ipynb_ and the following error occurs:
`AttributeError: module 'tensorflow' has no attribute 'function'`

**Describe the expected behavior**
I expected no errors during import of the module.

**Code to reproduce the issue**  
`from tensortrade.strategies import TensorforceTradingStrategy `

**Other info / logs**  
I started a Docker container and executed the commands, c.f. 
[trace.txt](https://github.com/notadamking/tensortrade/files/3580672/trace.txt)

**Comment by notadamking** [comment]
@andy121090 Have you tried updating to the latest version of TensorTrade?

**Comment by andy121090** [comment]
I was installing TensorTrade via `pip install tensortrade` and the version I get there is `0.0.1a3`.
Using the newly updated requirements.txt I get a different error:

`AttributeError: attribute '__isabstractmethod__' of 'staticmethod' objects is not writable`
([trace2.txt](https://github.com/notadamking/tensortrade/files/3587473/trace2.txt))

Is the pip installation of TensorTrade favoured? Or should it be imported directly from the source?

**Comment by notadamking** [comment]
The latest version is `0.0.1a4`, though I will be pushing an update later today fixing any issues with the tutorial.
