### ISSUE TITLE
Support for symmetric action space 

### ISSUE THREAD

**Issue by hn2** [notadamking/tensortrade#109]
Do you have plans to support symmetric action space of type Box required for table baseline models such as SAC or DDPG?
I tried this:
action_scheme = ContinuousActions(instrument='ETH/BTC')
strategy = StableBaselinesTradingStrategy(environment=environment, model=SAC, policy=LnMlpPolicy, tensorboard_log='log_1' )

But got:
AssertionError: Error: the action space low and high must be symmetric

This is because:
ContinuousActions has super().__init__(action_space=Box(0, 1, shape=(1, 1), dtype=dtype), dtype=dtype)

In addition, I tried adding tensorboard_log to stable baselines agent params:

params = { "gamma": 0.99, "tensorboard_log": "my_tensorboard_log"}

agent = model(policy, environment, **params)

But I do not see that it writes a tensorboard log while running the strategy.
Is it supported? Am I doing something wrong?

Also, Is it possible to have a window of features, for example suppose I want RSI of period -1, -2, -3, -4, -5, in other words a window of 5 periods of features? Is it possible?

**Comment by notadamking** [comment]
Should be possible now after #125 is merged
