### ISSUE TITLE
Tensortrade uses tensorflow 2 but tensorforce in tensorforce_trading_strategy.py doesn't work in tf version 2

### ISSUE THREAD

**Issue by Medicmind** [notadamking/tensortrade#11]
Tensortrade uses tensorflow 2 but tensorforce_trading_strategy.py has a tensorforce dependency which will not work with tensorflow 2. Wondering how to get the trading strategy to work.

**Comment by notadamking** [comment]
@Medicmind, the framework was originally created with the intentions of using TF 2, but unfortunately much of the reinforcement learning projects still require TF 1 (tensorforce, ray, stable-baselines, etc.).

For that reason, the framework is current limited to `tensorflow==1.14.0`.
