### ISSUE TITLE
'data type not understood' error in cctx_exchange.py

### ISSUE THREAD

**Issue by Medicmind** [notadamking/tensortrade#13]
When I try to run TensorTrade_Tutorial I am getting a 'data type not understood ' error.

In exchanges/live/ccxt_exchange.py it has
`
return Box(low=low, high=high, shape=obs, dtype=dtypes)
`
where dtypes is an array of data types but gym Box expect dtype to be a single datatype:

`
self.dtype = np.dtype(dtype)
`
and get a 'data type not understood error' at this line when I run the tutorial

**Comment by notadamking** [comment]
Looks like `gym` spaces only accept a single `dtype`, will fix.
