### ISSUE TITLE
For live trading, when will the environment start to execute the step function?

### ISSUE THREAD

**Issue by ramoslin** [notadamking/tensortrade#130]
Question.

For live trading, when will the environment start to execute the step function? And when will the environment ask the observation (the ohlcv data from the live exchange)?  I did not understand how the framework execute. Thanks and best regards.

**Comment by notadamking** [comment]
Please ask questions on the discord.

**Comment by zhnagchulan** [comment]
> Question.
> 
> For live trading, when will the environment start to execute the step function? And when will the environment ask the observation (the ohlcv data from the live exchange)? I did not understand how the framework execute. Thanks and best regards.

Have you solved this question? I have same problems for this.
