### ISSUE TITLE
tensortrade/strategies/__init__.py should be .tensorforce_trading_strategy import TensorforceTradingStrategy

### ISSUE THREAD

**Issue by Medicmind** [notadamking/tensortrade#14]
In order to get Tensortrade_Tutorial to work

tensortrade/strategies/__ init __.py

should be changed from

`from .trading_strategy import TradingStrategy`
`from .tensorforce_strategy import TensorforceStrategy`

to

`
from .trading_strategy import TradingStrategy`
`from .tensorforce_trading_strategy import TensorforceTradingStrategy
`

**Comment by andy121090** [comment]
Same here if importing TensorTrade directly from source:

`ModuleNotFoundError: No module named 'tensortrade.strategies.tensorforce_strategy'`

However, in the TensorTrade_Tutorial.ipynb the pip installation is suggested, but then other errors occur, c.f. #10.

**Comment by notadamking** [comment]
Nice catch.
