### ISSUE TITLE
Tensorforce renamed some things

### ISSUE THREAD

**Issue by K-Kit** [notadamking/tensortrade#18]
@notadamking It seems tensorforce is pushing updates changing a lot of things in their code base.

`Agent.from_spec()` changed and renamed to `Agent.create()`
https://github.com/tensorforce/tensorforce/commit/5cc4d236c70950997ecad279ba3c4b1b91d09fc0#diff-ce5c378eac1e50a69b6ff9b81a928974

**Comment by notadamking** [comment]
Looks like this was released yesterday - I will look into updating TensorforceTradingStrategy.

**Comment by K-Kit** [comment]
It seems a lot changed. a few things to save you a few minutes:

- They removed (maybe temporarily?)  OpenAIGym used in trading_environment.py (temp fix in my branch below) 

- the create function has some different args
I started to refactor but got stuck with this error and didn't know enough about the model to make it past
`raise TensorforceError.required(name=(value_type + ' spec'), value='num_values')
tensorforce.exception.TensorforceError: Missing action spec value: num_values.`


 https://github.com/K-Kit/tensortrade/blob/tensorforce-updates/tensortrade/strategies/tensorforce_trading_strategy.py

There could be more areas effected but this is as far as I got today

**Comment by notadamking** [comment]
I have created the https://github.com/notadamking/tensortrade/tree/tensorforce0.5.1-upgrade branch to address these changes.

**Comment by notadamking** [comment]
Implemented in #45
