### ISSUE TITLE
AttributeError: type object 'Agent' has no attribute 'from_spec'

### ISSUE THREAD

**Issue by forhonourlx** [notadamking/tensortrade#27]
Hi Adam,

I found the following exception, is that a version problem?
Thanks.

Traceback (most recent call last):
  File "train_and_evaluation.py", line 62, in <module>
    strategy = TensorforceTradingStrategy(environment=environment, agent_spec=agent_spec, network_spec=network_spec)
  File "/home/simon/anaconda3/lib/python3.6/site-packages/tensortrade/strategies/tensorforce_trading_strategy.py", line 50, in __init__
    self._agent = Agent.from_spec(spec=agent_spec,
AttributeError: type object 'Agent' has no attribute 'from_spec'

**Comment by Z-slim** [comment]
I ran into the same problem with Tensorforce 0.5.1, downgraded to version 0.4.4 and it fixed the issue for me along with the 'from tensorforce.contrib.openai_gym import OpenAIGym' issue I was having.

**Comment by codeninja** [comment]
`Agent.from_spec(spec=agent_spec)`

is now

`        self._agent = Agent.create(agent=self._agent_spec,
                                        environment=self._environment,
                                        kwargs=dict(network=network_spec,
                                                    states=environment.states(),
                                                    actions=environment.actions()))
`

in tensorflow 0.5.1

Another change would be needed in trading_environment.py 

`OpenAIGym.state_from_space(..)` 

is now

`OpenAIGym.specs_from_gym_space(self.observation_space, ignore_value_bounds=False)`

**Comment by notadamking** [comment]
@codeninja check out https://github.com/notadamking/tensortrade/tree/tensorforce0.5.1-upgrade
