### ISSUE TITLE
Upgrade to Tensorforce 0.5.1

### ISSUE THREAD

**Issue by codeninja** [notadamking/tensortrade#37]
With the release of Tensorforce 0.5.1 there are some major refactors needed. This issue request will track the work towards that goal.

A brief overview of the work required.

- Tensorforce architectural changes, method changes, and refactors will necessitate the restructuring of the environment and strategy classes as some methods and interactions have moved around.
- TF now has a new interface for OpenAIGym methods.
- Various example and tutorial scrips will need to be adjusted.

**Comment by notadamking** [comment]
Done by #45
