### ISSUE TITLE
ModuleNotFoundError: No module named 'talib'

### ISSUE THREAD

**Issue by sleekmike** [notadamking/tensortrade#38]
**System information**
Mac OS Mojave 10.14

- Have I written custom code (as opposed to using example directory):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorTrade version: 0.0.1a17
- TensorFlow version: 1.13.2
- Python version:3.7
- CUDA/cuDNN version:
- GPU model and memory:

Hello, 
I have been trying to run the Tensortrade examples both locally and on Google Colab but I have been getting this error:
ModuleNotFoundError: No module named 'talib'
 please how do I resolve this immediately. Thanks

**Comment by notadamking** [comment]
`pip install tensortrade[talib]`

**Comment by fbeenaerts** [comment]
On Google Colab, that doesn't work. I tried next and up till now, it seems to be OK (thanks to https://stackoverflow.com/users/6729010/korakot-chaovavanich)

!wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
!tar -xzvf ta-lib-0.4.0-src.tar.gz
%cd ta-lib
!./configure --prefix=/usr
!make
!make install
!pip install Ta-Lib

**Comment by sleekmike** [comment]
thanks a lot @fbeenaerts let me give it a try.

**Comment by sleekmike** [comment]
I was actually Able to fix the ta-lib issue by running the following commands on my Mac OS:
command:     brew install ta-lib
command:     pip install TA-Lib

for window, Linux and google collab check out this links:
https://stackoverflow.com/questions/52302861/how-do-i-install-ta-lib-in-python-3-in-mac-os-high-sierra

https://mrjbq7.github.io/ta-lib/install.html

**Comment by carlomigs** [comment]
I have a simpler solution:
!pip install talib-binary
Not sure if it works the same but it seems to have eliminated all the talib-related errors i was previously experiencing.

**Comment by cicorias** [comment]
unfortunately @carlomigs that doesn't work for macOS as that talib-binary is for Linux

**Comment by amitach** [comment]
I had the same issue on Big Sur again, 
Downloaded the source from [TALIB_SOURCE](https://mrjbq7.github.io/ta-lib/install.html)

- untar/unzip the download

- cd into the folder and run:

```
pip install -r requirements.txt
python setup.py install
```

import talib should now work

**Comment by yuzhupeng** [comment]
> I had the same issue on Big Sur again,
> Downloaded the source from [TALIB_SOURCE](https://mrjbq7.github.io/ta-lib/install.html)
> 
> * untar/unzip the download
> * cd into the folder and run:
> 
> ```
> pip install -r requirements.txt
> python setup.py install
> ```
> 
> import talib should now work

same as yours

**Comment by carlgoodier** [comment]
File "junk1.py", line 4, in <module>
    import talib
  File "/Users/cg/Downloads/ta-lib/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
ModuleNotFoundError: No module named 'talib._ta_lib'

> On Google Colab, that doesn't work. I tried next and up till now, it seems to be OK (thanks to https://stackoverflow.com/users/6729010/korakot-chaovavanich)
> 
> !wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz !tar -xzvf ta-lib-0.4.0-src.tar.gz %cd ta-lib !./configure --prefix=/usr !make !make install !pip install Ta-Lib

Thanks for your post.... 

I am on Catalina and jumped through every hoop i could find. Followed your procssess above, but with Make Install it would not let me as /usr is SIP protected.

thought it would be quite simple with CSRUTIL, but things are not a simple.... finally could unprotect, and unprotect folder by folder....

but :(

  File "junk1.py", line 4, in <module>
    import talib
  File "/Users/cg/Downloads/ta-lib/talib/__init__.py", line 93, in <module>
    from ._ta_lib import (
ModuleNotFoundError: No module named 'talib._ta_lib'

any advice appreciated

**Comment by QiutingWang** [comment]
```
!wget https://launchpad.net/~mario-mariomedina/+archive/ubuntu/talib/+files/libta-lib0_0.4.0-oneiric1_amd64.deb -qO libta.deb
!wget https://launchpad.net/~mario-mariomedina/+archive/ubuntu/talib/+files/ta-lib0-dev_0.4.0-oneiric1_amd64.deb -qO ta.deb
!dpkg -i libta.deb ta.deb
!pip install ta-lib
```
This one will be better~
