### ISSUE TITLE
Bug: Feature transforms are very slow

### ISSUE THREAD

**Issue by inetlab** [notadamking/tensortrade#40]
MinMaxNormalizer.transform: 0.4 sec on 5 feature columns

FractionalDifference takes almost 2s to transform 5 feature columns
History size was about 1000 elements at this moment, see log below 

-- FractionalDifference: transform
  
  -- FractionalDifference: fractional_difference
    -- FractionalDifference: difference_weights size: 936 took 0.000429
  -- FractionalDifference: fractional_difference: took 0.255751
  
  -- FractionalDifference: fractional_difference
    -- FractionalDifference: difference_weights size: 936 took 0.000367
  -- FractionalDifference: fractional_difference: took 0.258471
  
  -- FractionalDifference: fractional_difference
    -- FractionalDifference: difference_weights size: 936 took 0.000366
  -- FractionalDifference: fractional_difference: took 0.255252
  
  -- FractionalDifference: fractional_difference
    -- FractionalDifference: difference_weights size: 936 took 0.000413
  -- FractionalDifference: fractional_difference: took 0.253747
  
  -- FractionalDifference: fractional_difference
    -- FractionalDifference: difference_weights size: 936 took 0.000382
  -- FractionalDifference: fractional_difference: took 0.256269

-- FractionalDifference transform: took 1.836753

**Comment by notadamking** [comment]
Have you diagnosed more about why this is happening @inetlab?

**Comment by inetlab** [comment]
not too careful, but seems using high level pandas API slow it down a lot

**Comment by YasserHassan** [comment]
I confirm that this issue still exists. Here's a runnable example:
```
# Run in a Jupyter Notebook in TensorTrade examples directory.
import pandas as pd
from tensortrade.features.stationarity import FractionalDifference

df = pd.read_csv('data/Coinbase_BTCUSD_1h.csv', skiprows=1)
print('Data shape:', df.shape)

# Timing processing all columns.
difference_all = FractionalDifference(difference_order=0.6)
%time df2 = difference_all.transform(df)

# Timing processing a single column.
difference_all = FractionalDifference(difference_order=0.6)
%time df2 = difference_all.transform(df[['open']])
```
Result:
> Data shape: (20111, 8)
> CPU times: user 1min 42s, sys: 2min 13s, total: 3min 56s
> Wall time: 40.7 s
> CPU times: user 17.1 s, sys: 23.1 s, total: 40.2 s
> Wall time: 6.93 s

I traced the problem and found it resulting form this code part: https://github.com/notadamking/tensortrade/blob/07f32447ef80d012a274623be5ebca4af03ceb25/tensortrade/features/stationarity/fractional_difference.py#L82-L83
