### ISSUE TITLE
Bug: On Google Colab, KeyError: 'ppo_agent' 

### ISSUE THREAD

**Issue by fbeenaerts** [notadamking/tensortrade#47]
After: 
strategy = TensorforceTradingStrategy(environment=environment,                                       agent_spec=agent_spec, network_spec=network_spec)

I get the above error: KeyError: 'ppo_agent'

I think that in declaration of agent_spec, the "type" : "ppo_agent" should be replaced by "type": "ppo"

**Comment by fbeenaerts** [comment]
After: 
strategy = TensorforceTradingStrategy(environment=environment,                                       agent_spec=agent_spec, network_spec=network_spec)

I get the above error: KeyError: 'ppo_agent'

I think that in declaration of agent_spec, the "type" : "ppo_agent" should be replaced by "type": "ppo"

**Comment by junfang2019** [comment]
from tensorforce.agents import Agent
from tensorforce.environments import Environment
from tensortrade.environments import TradingEnvironment
from tensortrade.exchanges.simulated import FBMExchange
from tensortrade.features.scalers import MinMaxNormalizer
from tensortrade.features.stationarity import FractionalDifference
from tensortrade.features import FeaturePipeline
from tensortrade.rewards import SimpleProfitStrategy
from tensortrade.actions import DiscreteActionStrategy
from tensortrade.strategies import TensorforceTradingStrategy

normalize = MinMaxNormalizer(inplace=True)
difference = FractionalDifference(difference_order=0.6, inplace=True)
feature_pipeline = FeaturePipeline(steps=[normalize,difference])
reward_strategy = SimpleProfitStrategy()
action_strategy = DiscreteActionStrategy(n_actions=20, instrument_symbol='ETH/BTC')

exchange = FBMExchange(base_instrument='BTC', timeframe='1h', should_pretransform_obs=True)

environment = TradingEnvironment(exchange=exchange,
                                action_strategy=action_strategy,
                                reward_strategy=reward_strategy,
                                feature_pipeline=feature_pipeline)
agent_spec = {
    "type": "ppo_agent",
    "step_optimizer": {
        "type": "adam",
        "learning_rate": 1e-4},
    "discount": 0.99,
    "likelihood_ratio_clipping": 0.2,
}

network_spec = [
    dict(type='dense', size=64, activation="tanh"),
    dict(type='dense', size=32, activation="tanh")
]

agent = Agent.from_spec(spec=agent_spec,
                        kwargs=dict(network=network_spec,
                                    states=environment.states,
                                    actions=environment.actions))
agent

strategy = TensorforceTradingStrategy(environment=environment,
                                      agent_spec=agent_spec,
                                      network_spec=network_spec)

performance = strategy.run(episodes=1,testing=True)

performance[-5:]


---
with the code above, on Mac, found the same error.

**Comment by simonesalvucci** [comment]
After looking into the Tensoforce clases I came up with this:

- ppo_agent should be replaced by "type": "ppo"  as @fbeenaerts said
- step_optimizer is not part of a TensorForce Agent and shouldn't be used I think.
- learning_rate is taken out from step_optimizer as it is still needed
- max_episode_timesteps is added a per TensorForce agent

Doing so solves the error
`agent_spec = dict(type='ppo', learning_rate=1e-4, discount=0.99, likelihood_ratio_clipping=0.2, max_episode_timesteps=10000)`
