### ISSUE TITLE
Bug: Attribute '__isabstractmethod__' of 'staticmethod' objects is not writable in /examples

### ISSUE THREAD

**Issue by Kalelv45** [notadamking/tensortrade#53]
running tutorial I get this error
while trying to import tensortrade.strategies 
i get the following: 

attribute '__isabstractmethod__' of 'staticmethod' objects is not writable

how do I fix this?

**Comment by notadamking** [comment]
How were you running the tutorial: Google colab or jupyter notebook?
Were you running the tutorial in Docker?
