### ISSUE TITLE
Improve confusing terminology

### ISSUE THREAD

**Issue by andreskull** [notadamking/tensortrade#7]
The variables `symbol`, `base_symbol` and `output_symbol` are not used consistently in the code and it reduces the readability. actually `base_symbol` and `output_symbol` are the same. `output_symbol` should be renamed to `base_symbol` because this is more intuitive. Somewhere in the code variable name `symbol` is used where `base_symbol` is meant actually.

Those changes are implemented in https://github.com/notadamking/tensortrade/pull/6

**Comment by notadamking** [comment]
This should be fixed with the latest commits.
