### ISSUE TITLE
Feature Request: Keep the main package dependencies to the minimum

### ISSUE THREAD

**Issue by hohl** [notadamking/tensortrade#75]
**Summary**
Do not include the `TensorforceTradingStrategy` and the `StableBaselineTradingStrategy` in the main Tensortrade package. Right now, one has to install Tensorforce and Stable-Baselines packages even if he would use something total different (like a PyTorch-based implementation), just because all strategies get initialized when loading the `tensortrade` module.

**System information**
Not relevant for this issue.

**Describe the current behavior**
Right now `tensorflow`, `tensorforce` and `stable-baselines` packages need to be installed just to load the `tensortrade` module. Even if you are not going to use them, for example, when you want to use your own trading strategy based on PyTorch.

**Describe the expected behavior**
Split `tensortrade` into multiple PyPi-packages. `tensortrade` could be the main package and `tensortrade-tensorforce` could implement the `tensorforce`-based trading strategy. 

Another solution would be to just not automatically initialize all available trading strategies when loading the module. Or, check whether the dependency is installed before registering the corresponding trading strategy.

**Code to reproduce the issue**  
Not relevant for this issue.

**Comment by notadamking** [comment]
Does your PR fix this issue?

**Comment by hohl** [comment]
Yes, thanks for accepting it.
