### ISSUE TITLE
example TensorTrade_Tutorial.ipynb contains a few compile errors

### ISSUE THREAD

**Issue by maochaokuo** [notadamking/tensortrade#77]
Hi:

Would you mind take a look at Github tensortrade / examples / TensorTrade_Tutorial.ipynb? (the jupyter notebook file). There are already a few compile-time errors in the original tutorial. I tried to follow the "Trade and Invest Smarter — The Reinforcement Learning Way" article, but failed to finish a simplest beginning example at all. Would you mind to make a workable simplest example for the TensorTrade library? It looks like a very great trading library. It will be too bad not having good help for interested beginners (like me). 
Another problem is, if I start from "Putting it All Together" in TensorTrade_Tutorial.ipynb, I will get an error:
KeyError: 'ppo_agent'
at the line:
strategy = TensorforceTradingStrategy(environment=environment,
                                      agent_spec=agent_spec,
                                      network_spec=network_spec)
Please refer to the attached image.
![ppo_agent-error](https://user-images.githubusercontent.com/6857537/67636727-750aa100-f90e-11e9-80fc-8a901d1c06c9.png)

Thanks!

**Comment by notadamking** [comment]
There are some code snippets that aren't meant to run. I will go through the tutorial today and mark these correctly, so they do not produce errors.

**Comment by notadamking** [comment]
Should be all fixed now.
