### ISSUE TITLE
General question - Custom InstrumentExchange and ActionStrategy

### ISSUE THREAD

**Issue by wajihmsedi** [notadamking/tensortrade#83]
@notadamking I am not reporting an issue. I do have though two questions : 
- how do you instantiate a trading environment with your own observations (maybe a constructor for InstrumentExchange ?)
-For actionstrategy can you do anything else then hold buy or sell. Can you for instance fix the volatility of your portfolio ? 

Let me know if I need to clarify my question.

**Comment by notadamking** [comment]
Hi @wajihmsedi, for future reference, there is an active discord with over 100 members who would be happy to answer your questions and work with you on a solution.

1. To instantiate environments with your own observations, you can pass a custom `data_frame` to a `SimulatedEnvironment`.

2. `ActionStrategy`'s can do whatever you program them to do. If you need more than is available in `TradeType`, go ahead and create a custom `TradeType`, but at that point you will likely need to implement a custom `InstrumentExchange` and `RewardStrategy` as well.

**Comment by wajihmsedi** [comment]
Hi @notadamking.

Thank you for your answer.
How to join the discord group ?
On number 2 is tensortrade supporting creation of own `TradeType` ? Going forward how is it with `InstrumentExchange` and `RewardStrategy` ? 
I am new to reinforcement learning but went through the theory. I want to get my hands dirty now :)
