### ISSUE TITLE
MinMaxNormalizer with dtype=np.float16 Results in all Zero Observations from Feature Transformer

### ISSUE THREAD

**Issue by RaedShabbir** [notadamking/tensortrade#92]
In CCXT exchange the bounding box is created in the generated_spaces method, 

`high_price = float(self._markets[self._observation_symbol]['limits']['price']['max'])

= 1,000,000

np.float16(high_price) = inf`

The resulting step in minmax normalizer thus pushes everything to zero by dividing by inf, 

`normalized_column = (X[column] - low) / (high - low) * scale`

where high is inf.

**Comment by notadamking** [comment]
Fixed in #125
