### ISSUE TITLE
Window Size Indexing Bug In Simulated Exchange Results in First Observation Being Input Twice Into Feature Transformer  

### ISSUE THREAD

**Issue by RaedShabbir** [notadamking/tensortrade#93]
<em>Please make sure that this is a Bug or a Feature Request and provide all applicable information asked by the template.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/tensortrader) or on the [TensorTrade Discord](https://discord.gg/ZZ7BGWh) #help-desk channel instead of opening a GitHub issue.</em>

**System information**

- Have I written custom code (as opposed to using example directory):
- OS Platform and Distribution (e.g. Mac Sierra, Windows 10, Linux Ubuntu 16.04):
- TensorTrade version:
- TensorFlow version:
- Python version:

You can obtain the TensorFlow version with:  
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**  
Current Implementation

`
lower_range = max((self._current_step - self._window_size, 0))
upper_range = max(min(self._current_step, len(self._data_frame)), 1)
obs = self._data_frame.iloc[lower_range:upper_range]
`
window size = 10 
so current_step = 0
lower_range = 0
upper_range = 1 

current_step = 1
lower_range = 0 
upper_range = 1 

Hence the same index is passed 

proposed solution:
`
lower_range = max((self._current_step - self._window_size, 0))
upper_range = min(self._current_step, self._current_step, len(self._data_frame))
obs = self._data_frame.iloc[lower_range:upper_range+1]
`
Can push the solution, maintains a consistent spacing and window size

**Comment by notadamking** [comment]
Fixed in latest commit.
